# trunk-ignore-all(checkov/CKV_K8S_21): The namespace is managed by Kustomize and the kustomization.yaml
# trunk-ignore-all(checkov/CKV2_K8S_5): Argotails needs to be able to manage ArgoCD cluster's secrets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argotails
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argotails
rules:
  - apiGroups: [""]
    resources: [secrets]
    verbs: [get, list, watch, create, update, patch, delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argotails-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argotails
subjects:
  - kind: ServiceAccount
    name: argotails
