name: ğŸ¹ Build Argotails

on:
  merge_group: {}
  pull_request:
    types: [opened, synchronize]
    paths:
      - "**/*.go"
      - go.mod
      - go.sum
      - .github/workflows/pull_request,push.go.yaml
  push:
    branches: [main]

concurrency:
  group: ${{ github.action }}-${{ github.event.pull_request.id }}
  cancel-in-progress: true
permissions: {}

jobs:
  go-test:
    name: ğŸ§ª Test for go '${{ matrix.go }}' on '${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        go: [1.24]
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: ğŸš§ Setup Golang ${{ matrix.go }}
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: ${{ matrix.go }}
      - name: â¬‡ï¸ Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: ğŸ§ª Run all tests on ${{ matrix.os }}
        run: go test -v -race ./...
