name: ğŸ¹ Build Argotails

on:
  merge_group: {}
  pull_request:
    types: [opened, synchronize]
    paths:
      - "**/*.go"
      - go.mod
      - go.sum
      - .github/workflows/pull_request,push.go.yaml
  push:
    branches: [main]

concurrency:
  group: ${{ github.action }}-${{ github.event.pull_request.id }}
  cancel-in-progress: true
permissions: {}

jobs:
  go-test:
    name: ğŸ§ª Test for go '${{ matrix.go }}' on '${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        go: [1.24]
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: ğŸš§ Setup Golang ${{ matrix.go }}
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: ${{ matrix.go }}
      - name: â¬‡ï¸ Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: ğŸ§ª Run all tests on ${{ matrix.os }}
        run: go test -v -race ./...
