name: ğŸ”’ï¸ Security hardening (Github Actions workflows)

on:
  merge_group: {}
  pull_request:
    types: [opened, synchronize]
    paths: [.github/workflows/**]

permissions: {}

jobs:
  ci_harden_security:
    name: ğŸ”’ï¸ Github Action security hardening
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: â¬‡ï¸ Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: ğŸ“„ Lint Github Actions
        run: |
          curl -O https://raw.githubusercontent.com/rhysd/actionlint/4f6274a8e0f4f4d2057aa9ae07660f61aa29c5f3/.github/actionlint-matcher.json

          echo "::add-matcher::actionlint-matcher.json"
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/4f6274a8e0f4f4d2057aa9ae07660f61aa29c5f3/scripts/download-actionlint.bash)
          ./actionlint -color

      - name: âœ… Ensure SHA pinned actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@4830be28ce81da52ec70d65c552a7403821d98d4 # v3
